name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.6.6'
          projectPath: '/Users/thanh.pnguyen/Documents/Katalon/Mobile testing'
          args: '-browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -statusDelay=15 -testSuitePath="Test Suites/New Test Suite" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
